### ISSUE TITLE
Azken puntu berria

### ISSUE THREAD

**Issue by ZiTAL** [erral/azken_puntua#1]
- Bertsolaria: Amets Arzalluz
- Bideo/Audioa, bideo edo audioa nonbaiten argitaratuta badago, bertsoa.eus edo youtuben adibidez, itsatsi hemen helbidea: https://bertsoa.eus/albisteak/9120-amets-arzallusen-finala
- Azken puntuaren testua:

ta ibili gabe inori pasaporterik eskatzen
euskaratik has gaitezen bizitza oro askatzen

**Comment by erral** [comment]
Zerrendara gehituta, eskerrik asko!
